### ISSUE TITLE
Testing w/o Internet

### ISSUE THREAD

**Issue by sarahmehmedi** [larpfairy/twittermessage#1]
I liked how the code was commented so that I could understand what was going on. One thing I noticed is that when a user does not have internet (not sure if you were trying to make this a web only app), the LinksTest() function in **TwitterMessageTest.java** does not work and fails.

I believe this is because in **TwitterMessage.java** the function that starts in 
lines 85 to 101: `public boolean pingUrl(String Url)
`
requires internet connection to be able to work because it is checking the web to see if the url is valid or not. One way to fix this could be to parse the string to see if "http://, https://, www." pop up, instead of checking through internet connection for a valid url.

**Comment by jthompson18** [comment]
@sarahmehmedi, the implementation that @larpfairy used is fundamentally different from your suggested parsing of the string. The implementation used not only verifies that the string is a URL it also verifies that it corresponds to an actual URL that returns any type of data. @larpfairy is ignoring URLs that  don't acknowledge the ping, i.e invalid URLs.

**Comment by sarahmehmedi** [comment]
@jthompson18 yes it is a good approach to check for valid URLs. However, I was taking into consideration the idea of what if the user did not have internet. If a user did not have internet, then the program would not be able to check if the URL is even valid and would not be able to show the URLs (valid or not).

**Comment by jthompson18** [comment]
@sarahmehmedi because this is java code it will most likely be server side and the user's internet connection would not be relevant. With your comment it mind, the validity of this issue comes down to @larpfairy's intention for this code, wether this is seen as part of a standalone desktop app or some sort of client-server set up (either desktop client or webapp). Hopefully @larpfairy will respond on #3 with an answer that will clear this up.

**Comment by mgibbons2** [comment]
@jthompson18 @sarahmehmedi Thank you guys for the fantastic feedback. And to answer your question John, my intention is to go the webapp route. As far as what exactly I will use to accomplish this I am still deciding, and @sarahmehmedi your feedback was well intentioned and I would definitely take it if I was making this a desktop app.
