### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jthompson18** [larpfairy/twittermessage#3]
@larpfairy Your implementation is sound, but there is room for growth.

Your pingUrl method doesn't really make sense in the twitterMessage class. I'd like to see that living in some other url validation class. I assume you placed it there because it was the easy thing to do instead of making it part of another class and importing it.

Your parsing is extremely simple, this can be good and bad. Good, because it is able to handle a lot of possibilities as its a blanket solution. Bad, because it isn't written in an easily extendable way. For example, tour code only accounts for mentions that begin with '@' and contain any other char up to a space. It doesn't account for possible invalid characters in a mention or the length of the mention. If you needed to add either of these you'd have to write more code, adding in more string based parsing, than if you went with a regex based implementation. @larpfairy what was your reasoning for avoiding a regex based implementation, was there a specific reason for using string manipulations instead?

Your test cases are a bit lacking. I'd like to see more tests that use varying messages versus the one you used. As your code stands your really only testing one complete use case that you know will work. It is a good set up for some initial TDD but after the core functionality is there go back and make more tests that designed to test for edge cases. If the user enters "@mentionmentionmentionmentionmentionmentionmention #topic**((&#(@#&" will this crash the module? Currently this will not, but if that is good or not relates to my previous critique.

**Comment by jthompson18** [comment]
@larpfairy I almost forgot. 
What kind of system would do you see this fitting in? How did it influence your design of this module?

**Comment by mgibbons2** [comment]
Thanks for the feedback @jthompson18, you make a lot of very good points. I will make some changes soon to the structure of the app by moving the Pingurl method to its own class. Additionally I will improve upon the initially simple parsing and add much more testing, as testing was severely lacking initially.

**Comment by mgibbons2** [comment]
@jthompson18 ,
I have moved the pingUrl method to a Utilities class, implemented regex into the parsing methods, and have added many more test cases so as to cover more of my code. Thanks for the feedback once again.
