### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by csoulakian** [larpfairy/twittermessage#7]
I like that you included comments about each method and variable! They might be easier to see if you put them before the variable/method in block comments like this:

![untitled](https://cloud.githubusercontent.com/assets/10621461/12994604/898670b2-d0e7-11e5-9c31-55da8f3ed5db.jpg)

Also, adding a bit more to your readme might be helpful for others when viewing your code.

**Comment by mgibbons2** [comment]
Thanks for the feedback, I will make these documentation changes soon.
